### PR TITLE
Lazy load sources

### PR DESCRIPTION
**Pull request by gbjk**
Same as jhthorsen's original PR.
Rebased and fixed for changes since.

I'll be going through testing of this in the coming week.

### CODE REVIEW

**Comment by mcsnolte** [comment]
:+1: for this feature :smile:

**Comment by mcsnolte** [comment]
@gbjk did you have any more ideas on how to make this work?  Thanks

**Comment by gbjk** [comment]
I stopped sniffing at this as it felt like the substrate we'd built upon was unsettled.
I think if I recall correctly the issue was that we built this on a branch that didn't end up getting folded into a release at the time. I checked months later, and it still hadn't happened.
I think I need to touch base with @ribasushi about this. I would have done so at LPW but I was unfortunately not able to attend. I'll grab him some time soon to discuss.

For what it's worth, we've actually been running this in production for well over a year now.

**Comment by mcsnolte** [comment]
Nice!  Thanks for the update @gbjk

**Comment by ribasushi** [comment]
Am busy getting things into shape for 0.082830. Will make sure to post an update / future plan / holdup description for my successor before I sign off.

**Comment by gbjk** [comment]
StaleAF.

**Pull request closed without merging**
